Feature/22
LucasCalazans/react-commerce pull request #49
Opened 2019-03-12 11:14 UTC by 90lucasgabriel

2019-03-12 14:14 UTC, LucasCalazans requested changes

2019-03-12 14:14 UTC, LucasCalazans commented on src/components/Loader/index.jsx
> +    type ? type : (type = 'normal');
Utilizar o `default props` no desctructuring

2019-03-14 14:28 UTC, wesleyalmd approved these changes

2019-03-14 14:32 UTC, LucasCalazans approved these changes

2019-03-14 14:32 UTC, merged