19 - created ratings component
LucasCalazans/react-commerce pull request #51
Opened 2019-03-14 14:38 UTC by alvsgabriel

2019-03-14 14:49 UTC, wesleyalmd approved these changes

2019-03-14 14:49 UTC, wesleyalmd commented on src/App.jsx
> +import Rating from './components/Rating';
Remver o Rating

2019-03-14 14:49 UTC, wesleyalmd commented on src/components/Rating/index.jsx
> +    star_over = rating => {
houver

2019-03-14 14:49 UTC, wesleyalmd commented on src/App.jsx
> +            <Rating />
Remover

2019-03-14 14:49 UTC, wesleyalmd commented on src/components/Rating/index.jsx
> +class Index extends Component {
Chamar a classe de Rating faz mais sentido

2019-03-14 14:49 UTC, wesleyalmd commented on src/components/Rating/index.jsx
> +export default Index;
e aqui

2019-03-14 15:32 UTC, LucasCalazans requested changes

2019-03-14 15:32 UTC, LucasCalazans commented on src/components/Rating/__stories__/rating.js
> +    <Fragment>
Remove `Fragment`

2019-03-14 15:32 UTC, LucasCalazans commented on src/components/Rating/index.jsx
> +    star_hover = rating => {
Use `camelCase`

2019-03-14 15:32 UTC, LucasCalazans commented on src/components/Rating/index.jsx
> +        temp_rating: null,
Use `camelCase`

2019-03-14 15:32 UTC, LucasCalazans commented on src/components/Rating/index.jsx
> +    star_out = () => {
Use `camelCase`

2019-03-14 15:32 UTC, LucasCalazans commented on src/components/Rating/index.jsx
> +    rate = rating => {
Use `setRate` as the method name

2019-03-14 15:32 UTC, LucasCalazans commented on src/components/Rating/index.jsx
> +                    onClick={this.rate.bind(this, i)}
You don't need to use this `bind` because your method id using `arrow function`

2019-03-14 15:32 UTC, LucasCalazans commented on src/components/Rating/index.jsx
> +                    onMouseOver={this.star_hover.bind(this, i)}
You don't need to use this `bind` because your method id using `arrow function`

2019-03-14 18:08 UTC, wesleyalmd approved these changes

2019-03-14 18:08 UTC, wesleyalmd commented
@LucasCalazans, da um OK final nessa PR

2019-03-19 00:50 UTC, LucasCalazans commented
@alvsgabriel Ficou faltando a funcionalidade para quando estivermos usando o componente em uma listagem recebendo os valores da API.
Nesse caso você teria que receber um valor por propriedade e bloquear o uso (Hover e clique).

2019-03-19 14:46 UTC, wesleyalmd commented
@LucasCalazans, da um review final nessa issue

2019-03-19 15:06 UTC, LucasCalazans approved these changes

2019-03-19 15:07 UTC, merged