Feature/20 | Pagination
LucasCalazans/react-commerce pull request #81
Opened 2019-04-18 15:12 UTC by 90lucasgabriel

Feature/20 | Pagination
- New: Creating pagination;
- New: Creating styles file;
- Update: States to Props;
- Update: onChange();

2019-04-18 15:25 UTC, LucasCalazans requested changes

2019-04-18 15:25 UTC, LucasCalazans commented on src/components/Pagination/__stories__/pagination.jsx
> +import React, { Fragment } from 'react';
Remover Fragment, não está sendo utilizado

2019-04-18 15:25 UTC, LucasCalazans commented on src/components/Pagination/__stories__/pagination.jsx
> +            onChange={() => console.log('opa')}
Adicionar uma outra mensagem no console.log

2019-04-18 15:25 UTC, LucasCalazans commented on src/components/Pagination/index.jsx
> +    // Vars -------
Remover os comentários desse arquivo

2019-04-18 15:25 UTC, LucasCalazans commented on src/components/Pagination/index.jsx
> +import React, { Component } from 'react';
Mover a pasta Pagination para dentro de containers (Isso pq esse componente tem controle de estado)

2019-04-18 15:25 UTC, LucasCalazans commented on src/components/Pagination/styles.js
> +const arrowButton = css`
Utilizar o ArrowButton tanto para o Left quanto para o Right, já que eles são iguais

2019-04-23 17:18 UTC, LucasCalazans requested changes

2019-04-23 17:18 UTC, LucasCalazans commented on src/containers/Pagination/styles.js
> +    cursor: ${({ active, disable }) => (active, disable ? 'default' : 'pointer')};
Apesar de não estar dando erro, esse comando não está fazendo o que deveria. Ele está olhando apenas para a prop `disable` e ignorando o active. Nesse caso deveria ser um `or`
```suggestion
    cursor: ${({ active, disable }) => active || disable ? 'default' : 'pointer')};
```

2019-04-25 17:47 UTC, 90lucasgabriel commented on src/containers/Pagination/styles.js
> +    cursor: ${({ active, disable }) => (active, disable ? 'default' : 'pointer')};
Alterado para 'disabled'.

2019-04-25 18:05 UTC, LucasCalazans approved these changes

2019-04-25 18:05 UTC, merged