18 - creating a thumbnail component
LucasCalazans/react-commerce pull request #82
Opened 2019-04-23 15:02 UTC by alvsgabriel

2019-04-23 15:08 UTC, wesleyalmd submitted a review, later dismissed

2019-04-23 15:08 UTC, wesleyalmd commented on src/components/Thumbnail/index.jsx
> +import * as styles from './styles';
```suggestion
import { Thumbnail, ThumbnailRating, Discount, ThumbnailName, Price, SpecialPrice } from './styles';
```

2019-04-23 15:08 UTC, wesleyalmd commented on src/components/Thumbnail/index.jsx
> +    let price = props.product.price;
Talvez um deconstruct nos attrs

```suggestion
    const { price, specialPrice, rating } = props.product;
```

2019-04-25 17:30 UTC, LucasCalazans requested changes

2019-04-25 17:30 UTC, LucasCalazans commented on src/components/Rating/index.jsx
> +            const fill = value >= i && value != null ? '#cdb44d' : '#d7d7d7';
Utilizar as variáveis em helpers/styles

2019-04-25 17:30 UTC, LucasCalazans commented on src/components/Thumbnail/styles.js
> +    color: #707070;
Utilizar as variáveis em helpers/styles

2019-04-25 17:30 UTC, LucasCalazans commented on src/components/Thumbnail/styles.js
> +    color: #c70041;
Utilizar as variáveis em helpers/styles

2019-04-25 17:30 UTC, LucasCalazans commented on src/components/Thumbnail/styles.js
> +    color: #707070;
Utilizar as variáveis em helpers/styles

2019-04-25 17:30 UTC, LucasCalazans commented on src/components/Thumbnail/styles.js
> +    background-color: #c70041;
Utilizar as variáveis em helpers/styles

2019-04-25 17:30 UTC, LucasCalazans commented on src/components/Thumbnail/styles.js
> +    color: #ffffff;
Utilizar as variáveis em helpers/styles

2019-04-30 15:00 UTC, LucasCalazans approved these changes

2019-04-30 15:01 UTC, merged